/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import * as THREE from 'three'


export default function Model({ ...props }) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const colorMap = useLoader(TextureLoader, '/raw/icons/тест_знач/textures/konfeta.png')
  
  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });

  const { nodes, materials } = useGLTF('/raw/icons/тест_знач/konf3.gltf')
  return (
    <group>
      <group position={[6.09, 0.9, 2.5]} rotation={[Math.PI / 2, 0, 0]} scale={[2.44, 0.02, 2.44]}>
        <mesh geometry={nodes.Куб003.geometry} material={materials['Материал.007']}>
        <meshBasicMaterial map={colorMap} />
        </mesh>
        <mesh geometry={nodes.Куб003_1.geometry} material={nodes.Куб003_1.material} >
        <meshBasicMaterial map={colorMap} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/raw/icons/тест_знач/konf3.gltf')

