/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/fourteen/fourteen.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[0, 0.05, 0]} scale={[0.37, 0.17, 1.6]}
    position={[0.3, 0.2, 8.27]} >
            <mesh 
              geometry={nodes.Cube007.geometry}
              material={hovered ? mater : materials.Material}>
            </mesh>
            <mesh 
              geometry={nodes.Cube007_1.geometry}
              material={hovered ? mater : materials.Материал}>
            </mesh>
            <mesh 
              geometry={nodes.Cube007_2.geometry}
              material={hovered ? mater : materials['Материал.002']}>
            </mesh>   
    </group>
  )
}
useGLTF.preload('/raw/fourteen/fourteen.gltf')
