/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const ref = useRef()
  const [hovered, hover] = useState(false)

  const { nodes, materials } = useGLTF('/raw/longfield/longfield.gltf')
  return (
    <group>
      <mesh 
        material={materials['Материал.010']}
        geometry={nodes.Икосфера020.geometry}
        rotation={[Math.PI, -Math.PI / 10, Math.PI]}
        position={[-0.65, 0.45, 4.85]}
        scale={[0.1, 0.11, 0.12]}>
      </mesh>
      <mesh 
       material={materials['Материал.008']}
        geometry={nodes.Cube025.geometry}
        position={[-0.8, 0.03, 6.5]}
        rotation={[0, 0, Math.PI]}
        scale={[0.14, 0.08, 2.24]}>
      </mesh>
      <mesh 
        material={materials['Материал.009']}
        geometry={nodes.Икосфера002.geometry}
        position={[-0.635, 0.49, 8.29]}
        rotation={[Math.PI, -Math.PI / 10, Math.PI]} 
        scale={[0.11, 0.13, 0.14]}>
      </mesh>
    </group>
  )
}

useGLTF.preload('/raw/longfield/longfield.gltf')
