/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/*
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/pole.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.07, 0.19, 0.07]}>
        <mesh geometry={nodes.Цилиндр020.geometry} material={materials['Материал.010']} />
        <mesh geometry={nodes.Цилиндр020_1.geometry} material={materials['Материал.008']} />
      </group>
      <group position={[0, -0.12, 1.31]} scale={[0.22, 0.06, 0.22]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Материал.011']} />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} position={[-0.01, 0.67, 1.28]} rotation={[Math.PI, 0, Math.PI]} scale={0.04} />
    </group>
  )
}

useGLTF.preload('/pole.gltf')*/

import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/midfield/pole.gltf')
  
  return (
    <group ref={ref} {...props} dispose={null}
    position={[-1, 0.12, 0]}>
    <group scale={[0.07, 0.19, 0.07]}>
            <mesh 
              geometry={nodes.Цилиндр020.geometry}
              material={materials['Материал.010']}>
            </mesh>
            <mesh 
              geometry={nodes.Цилиндр020_1.geometry}
              material={materials['Материал.008']}>
            </mesh>  
    </group>
    <group scale={[0.22, 0.06, 0.22]} position={[0, -0.12, 1.31]}>
            <mesh 
              geometry={nodes.Cube_1.geometry}
              material={materials['Material.001']}>
            </mesh>
            <mesh 
              geometry={nodes.Cube_2.geometry}
              material={materials['Материал.011']}>
            </mesh>
           
    </group>
            <mesh rotation={[Math.PI, 0, Math.PI]} scale={0.04} position={[-0.01, 0.67, 1.28]}
              geometry={nodes.Sphere.geometry}
              material={materials['Material.002']}>
            </mesh>   
    </group>
  )
}
useGLTF.preload('/raw/midfield/pole.gltf')
