/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/nine/nine.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[Math.PI, Math.PI /2, 0]} scale={[0.04, 0.07, 0.001]}
    position={[5.18, 0.1, 3.75]}>
            <mesh 
              geometry={nodes.Куб013.geometry}
              material={hovered ? mater : materials['Материал.001']}>
            </mesh>
            <mesh 
              geometry={nodes.Куб013_1.geometry}
              material={hovered ? mater : materials['Материал.002']}>
            </mesh>
            <mesh 
              geometry={nodes.Куб013_2.geometry}
              material={hovered ? mater : materials['Материал.005']}>
            </mesh>   
            <mesh 
              geometry={nodes.Куб013_3.geometry}
              material={hovered ? mater : materials.Материал}>
            </mesh>  
    </group>
  )
}
useGLTF.preload('/raw/nine/nine.gltf')
