/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/seven/seven.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[0, 0, Math.PI]}
    position={[0, 0.2, 3.75]}
    scale={[0.27, 0.17, 0.25]}>
            <mesh 
              geometry={nodes.Cube015.geometry}
              material={hovered ? mater : materials.Material}>
            </mesh>
            <mesh 
              geometry={nodes.Cube015_1.geometry}
              material={hovered ? mater :  materials.Материал}>
            </mesh>
            <mesh 
              geometry={nodes.Cube015_2.geometry}
              material={hovered ? mater : materials['Материал.002']}>
            </mesh>   
    </group>
  )
}
useGLTF.preload('/raw/seven/seven.gltf')