/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const ref = useRef()
  const [hovered, hover] = useState(false)

  const { nodes, materials } = useGLTF('/testmodel/testmodel.gltf')
  return (

      <mesh 
        {...props}
        ref={ref}
        onPointerOver={(event) => hover(true)}
        onPointerOut={(event) => hover(false)}

        geometry={nodes.Cube035.geometry} 
        material={materials.text} 
        position={[0, 0, 0]} 
        rotation={[0, Math.PI / 2, 0, 0]} 
        scale={[0.01, 0.27, 0.19]} >
        <meshStandardMaterial color={hovered ? '#ffc800' : '#bababa'} />
      </mesh>

  )
}

useGLTF.preload('/testmodel/testmodel.gltf')
