/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const ref = useRef()
  const [hovered, hover] = useState(false)

  const { nodes, materials } = useGLTF('/raw/trianglefield/trianglefield.gltf')
  return (
    <group>
      <mesh 
        material={materials['Материал.010']}
        geometry={nodes.Цилиндр014.geometry}
        position={[8, 0.18, -3]}
        scale={[0.12, 0.32, 0.12]}>
      </mesh>
      <mesh 
        material={materials['Материал.009']}
        geometry={nodes.Plane017.geometry}
        rotation={[Math.PI, -0.57, Math.PI]}
        position={[8, 0.18, -3]}
        scale={[0.74, 0.38, 0.38]}>
      </mesh>
      <mesh 
        material={materials['Материал.002']}
        geometry={nodes.Cylinder005.geometry}
        position={[7.35, 0, -2.6]}
        scale={[-0.2, -0.04, -0.19]}>
      </mesh>
      <mesh 
        material={materials['Материал.009']}
        rotation={[Math.PI, -Math.PI / 10, Math.PI]}
        geometry={nodes.Икосфера009.geometry}
        position={[8, 0.18, -3.01]}
        scale={[0.12, 0.13, 0.14]}>
      </mesh>
    </group>
  )
}

useGLTF.preload('/raw/trianglefield/trianglefield.gltf')
