/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/twentyone/twentyone.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[0, 0.77, -Math.PI]} scale={[0.04, 0.07, 0.001]}
    position={[7, 0.13, -0.7]}>
            <mesh 
              geometry={nodes.Куб025.geometry}
              material={hovered ? mater : materials['Материал.005']}>
            </mesh>
            <mesh 
              geometry={nodes.Куб025_1.geometry}
              material={hovered ? mater : materials.Material}>
            </mesh>
            <mesh 
              geometry={nodes.Куб025_2.geometry}
              material={hovered ? mater : materials['Material.001']}>
            </mesh>  
            <mesh 
              geometry={nodes.Куб025_3.geometry}
              material={hovered ? mater : materials['Материал.001']}>
            </mesh>  
    </group>
  )
}
useGLTF.preload('/raw/twentyone/twentyone.gltf')