/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/twentyfour/twentyfour.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[Math.PI / 2, 0,Math.PI]} scale={[0.00225, 0.0075, 0.00225]}
    position={[0, 0.6, 4.45]}>
            <mesh 
              geometry={nodes.Cube024.geometry}
              material={hovered ? mater : materials['Material.003']}>
            </mesh>
            <mesh 
              geometry={nodes.Cube024_1.geometry}
              material={hovered ? mater :materials['Material.002']}>
            </mesh>
            <mesh 
              geometry={nodes.Cube024_2.geometry}
              material={hovered ? mater : materials['Material.001']}>
            </mesh>   
            <mesh 
              geometry={nodes.Cube024_3.geometry}
              material={hovered ? mater : materials['Материал.007']}>
            </mesh>
            <mesh 
              geometry={nodes.Cube024_4.geometry}
              material={hovered ? mater : materials.Материал}>
            </mesh>
            <mesh 
              geometry={nodes.Cube024_5.geometry}
              material={hovered ? mater : materials['Material.004']}>
            </mesh>   
            <mesh 
              geometry={nodes.Cube024_6.geometry}
              material={hovered ? mater : materials['Material.005']}>
            </mesh>   
    </group>
  )
}
useGLTF.preload('/raw/twentyfour/twentyfour.gltf')