/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/five/five.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    scale={[1.85, 0.18, 0.26]}
    position={[-5.1, 0.2, 0]}>
            <mesh 
              geometry={nodes.Cube036.geometry}
              material={hovered ? mater : materials['Материал.001']}>
            </mesh>
            <mesh 
              geometry={nodes.Cube036_1.geometry}
              material={hovered ? mater : materials.Материал}>
            </mesh>
    </group>
  )
}
useGLTF.preload('/raw/five/five.gltf')
