/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/raw/square-center/squarecenter.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.Plane001.geometry} 
        material={materials['Material.001']} 
        position={[-1, 0.03, -5]} 
        scale={0.7} />
    </group>
  )
}

useGLTF.preload('/raw/square-center/squarecenter.gltf')
