/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export default function Model({ ...props }, onClick = () => {}) {

  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/twentyfive/twentyfive.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[0, 1.57, 0]} scale={[0.33, 0.27, 0.33]}
    position={[0.1, 0.3, 5.07]}>
            <mesh 
              geometry={nodes.Cube012.geometry}
              material={hovered ? mater : materials['Material.001']}>
            </mesh>
            <mesh 
              geometry={nodes.Cube012_1.geometry}
              material={hovered ? mater : materials.Материал}>
            </mesh>
            <mesh 
              geometry={nodes.Cube012_2.geometry}
              material={hovered ? mater : materials['Материал.002']}>
            </mesh>   
    </group>
  )
}
useGLTF.preload('/raw/twentyfive/twentyfive.gltf')
