/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const ref = useRef()
  const [hovered, hover] = useState(false)

  const { nodes, materials } = useGLTF('/raw/twentysixtwentyseven/twentysixtwentyseven.gltf')
  return (
    <mesh 
      material={materials.Material}
      geometry={nodes.Cube021.geometry}
      position={[-3.8, 0.04, 5.9]}
      scale={[2.02, 0.02, 1.53]} >
    </mesh>
  )
}

useGLTF.preload('/raw/twentysixtwentyseven/twentysixtwentyseven.gltf')