/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model({ ...props }, onClick = () => {}) {
  const ref = useRef()
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF('/raw/two/two.gltf')

  const mater = new THREE.MeshStandardMaterial({ 
    color: 0xffe74d,
  });
  
  return (
    <group ref={ref} {...props} dispose={null}
    onPointerOver={(event) => hover(true)}
    onPointerOut={(event) => hover(false)}
    rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.16, 0.01]}
    position={[3.15, 1, 2.2]}>
            <mesh 
              geometry={nodes.Cylinder.geometry}
              material={hovered ? mater : materials['Материал.011']}>
            </mesh>
            <mesh 
              geometry={nodes.Cylinder_1.geometry}
              material={hovered ? mater : materials.Material}>
            </mesh>
            <mesh 
              geometry={nodes.Cylinder_2.geometry}
              material={hovered ? mater : materials['Material.001']}>
            </mesh>   
            <mesh 
              geometry={nodes.Cylinder_3.geometry}
              material={hovered ? mater : materials['Материал.010']}>
            </mesh>
            <mesh 
              geometry={nodes.Cylinder_4.geometry}
              material={hovered ? mater : materials['Material.003']}>
            </mesh>
            <mesh 
              geometry={nodes.Cylinder_5.geometry}
              material={hovered ? mater : materials['Material.002']}>
            </mesh>   
    </group>
  )
}
useGLTF.preload('/raw/two/two.gltf')